# Program to guess random number generated by the program

import random

secret = random.randint(1, 10)
print("Secret number is: {}".format(secret))

attemts = 0
while attemts < 2:
    try:
        guess = int(input("? "))
        attemts += 1
    except ValueError:
        continue
    if guess == secret:
        print("Ok!!")
        break
    elif guess < secret:
        print("<")
    else:
        print(">")
else:
    print("You are looser`")