# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_proto2.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11test_proto2.proto\"\x1c\n\x04Test\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"h\n\x04Item\x12\x18\n\x03key\x18\x01 \x01(\x0e\x32\x0b.Item.Key_t\x12\r\n\x03str\x18\x02 \x01(\tH\x00\x12\r\n\x03i32\x18\x03 \x01(\rH\x00\"\x1d\n\x05Key_t\x12\t\n\x05\x44\x41TA1\x10\x00\x12\t\n\x05\x44\x41TA2\x10\x01\x42\t\n\x07Value_t')
)



_ITEM_KEY_T = _descriptor.EnumDescriptor(
  name='Key_t',
  full_name='Item.Key_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA1', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA2', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=115,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_ITEM_KEY_T)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='Test.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=49,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Item.key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='Item.str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i32', full_name='Item.i32', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ITEM_KEY_T,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Value_t', full_name='Item.Value_t',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=51,
  serialized_end=155,
)

_TEST.fields_by_name['items'].message_type = _ITEM
_ITEM.fields_by_name['key'].enum_type = _ITEM_KEY_T
_ITEM_KEY_T.containing_type = _ITEM
_ITEM.oneofs_by_name['Value_t'].fields.append(
  _ITEM.fields_by_name['str'])
_ITEM.fields_by_name['str'].containing_oneof = _ITEM.oneofs_by_name['Value_t']
_ITEM.oneofs_by_name['Value_t'].fields.append(
  _ITEM.fields_by_name['i32'])
_ITEM.fields_by_name['i32'].containing_oneof = _ITEM.oneofs_by_name['Value_t']
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'test_proto2_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  ))
_sym_db.RegisterMessage(Test)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'test_proto2_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
